# SORTING 
# SELECT COLUMN1,COLUMN2 FROM  TABLENAME ORDER BY COLUMNNAME  ASCENDING
SELECT * FROM students ORDER BY AGE ASC;
SELECT * FROM students ORDER BY Name ASC;
SELECT * FROM students ORDER BY Name DESC;